#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if [ $GIT_DOMAIN ];then
    r=`git remote -v|awk '{print $2}'|grep $GIT_DOMAIN|wc -l`
    if [ $r -gt 0 ];then
        git remote  -v
        if test -z "$GIT_NAME";then
            git config user.name $GIT_NAME
        fi

        if [ ! $GIT_EMAIL ];then
            git config user.email $GIT_EMAIL
        fi
    fi
    unset r
fi
